### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by MisterDav** [Calastrophe/Discord-Token-Bruteforcer-Helper#1]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/misterdav/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "server.py", line 48, in on_ready
    file = f'''
ValueError: Invalid format specifier

**Comment by Calastrophe** [comment]
Not something on my end.
